"""semantic layer

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-05 10:22:39.938395+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0004'
down_revision: str | None = '0003'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimensions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('column', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_dimensions_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dimensions')),
    sa.UniqueConstraint('org_id', 'key', name=op.f('uq_dimensions_org_id'))
    )
    op.create_index(op.f('ix_dimensions_org_id'), 'dimensions', ['org_id'], unique=False)
    op.create_table('metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('table', sa.String(length=200), nullable=False),
    sa.Column('time_column', sa.String(length=200), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('filters', sa.Text(), nullable=False),
    sa.Column('maturity_days', sa.Integer(), nullable=False),
    sa.Column('default_dimensions', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('format', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('pack', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_metrics_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_metrics_source_id_data_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics')),
    sa.UniqueConstraint('org_id', 'key', name=op.f('uq_metrics_org_id'))
    )
    op.create_index(op.f('ix_metrics_org_id'), 'metrics', ['org_id'], unique=False)
    op.create_table('metric_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], name=op.f('fk_metric_versions_metric_id_metrics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_versions')),
    sa.UniqueConstraint('metric_id', 'version', name=op.f('uq_metric_versions_metric_id'))
    )
    op.create_index(op.f('ix_metric_versions_metric_id'), 'metric_versions', ['metric_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metric_versions_metric_id'), table_name='metric_versions')
    op.drop_table('metric_versions')
    op.drop_index(op.f('ix_metrics_org_id'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_dimensions_org_id'), table_name='dimensions')
    op.drop_table('dimensions')
    # ### end Alembic commands ###
