"""knowledge base

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-05 10:38:07.679899+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # array_to_string is only STABLE; generated columns need an IMMUTABLE expression
    op.execute(
        "CREATE OR REPLACE FUNCTION kb_tags_text(text[]) RETURNS text "
        "LANGUAGE sql IMMUTABLE PARALLEL SAFE AS $$ SELECT array_to_string($1, ' ') $$"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('links', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('source_ref', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('search', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('russian', coalesce(title, '')), 'A') || setweight(to_tsvector('russian', coalesce(summary, '')), 'B') || setweight(to_tsvector('russian', kb_tags_text(tags)), 'B') || setweight(to_tsvector('russian', coalesce(body, '')), 'C')", persisted=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_kb_items_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_kb_items_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_kb_items_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_items'))
    )
    op.create_index(op.f('ix_kb_items_org_id'), 'kb_items', ['org_id'], unique=False)
    op.create_index(op.f('ix_kb_items_project_id'), 'kb_items', ['project_id'], unique=False)
    op.create_index('ix_kb_items_search', 'kb_items', ['search'], unique=False, postgresql_using='gin')
    op.create_index('ix_kb_items_tags', 'kb_items', ['tags'], unique=False, postgresql_using='gin')
    op.create_index('ix_kb_items_title_trgm', 'kb_items', ['title'], unique=False, postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.create_table('kb_attachments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['kb_items.id'], name=op.f('fk_kb_attachments_item_id_kb_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_attachments'))
    )
    op.create_index(op.f('ix_kb_attachments_item_id'), 'kb_attachments', ['item_id'], unique=False)
    op.create_table('kb_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_kb_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['kb_items.id'], name=op.f('fk_kb_comments_item_id_kb_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_comments'))
    )
    op.create_index(op.f('ix_kb_comments_item_id'), 'kb_comments', ['item_id'], unique=False)
    op.create_table('kb_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['kb_items.id'], name=op.f('fk_kb_versions_item_id_kb_items'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_versions'))
    )
    op.create_index(op.f('ix_kb_versions_item_id'), 'kb_versions', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kb_versions_item_id'), table_name='kb_versions')
    op.drop_table('kb_versions')
    op.drop_index(op.f('ix_kb_comments_item_id'), table_name='kb_comments')
    op.drop_table('kb_comments')
    op.drop_index(op.f('ix_kb_attachments_item_id'), table_name='kb_attachments')
    op.drop_table('kb_attachments')
    op.drop_index('ix_kb_items_title_trgm', table_name='kb_items', postgresql_using='gin', postgresql_ops={'title': 'gin_trgm_ops'})
    op.drop_index('ix_kb_items_tags', table_name='kb_items', postgresql_using='gin')
    op.drop_index('ix_kb_items_search', table_name='kb_items', postgresql_using='gin')
    op.drop_index(op.f('ix_kb_items_project_id'), table_name='kb_items')
    op.drop_index(op.f('ix_kb_items_org_id'), table_name='kb_items')
    op.drop_table('kb_items')
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION IF EXISTS kb_tags_text(text[])")
