"""event registry

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-05 13:46:09.521216+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ems_global_params',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enum', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_ems_global_params_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ems_global_params')),
    sa.UniqueConstraint('org_id', 'name', name=op.f('uq_ems_global_params_org_id'))
    )
    op.create_index(op.f('ix_ems_global_params_org_id'), 'ems_global_params', ['org_id'], unique=False)
    op.create_table('notification_channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secrets_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('min_severity', sa.String(length=16), nullable=False),
    sa.Column('project_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_notification_channels_org_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_channels'))
    )
    op.create_index(op.f('ix_notification_channels_org_id'), 'notification_channels', ['org_id'], unique=False)
    op.create_table('ems_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('metric_keys', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String(length=64)), nullable=False),
    sa.Column('current_version', sa.String(length=32), nullable=True),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_ems_events_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ems_events_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ems_events')),
    sa.UniqueConstraint('project_id', 'name', name=op.f('uq_ems_events_project_id'))
    )
    op.create_index(op.f('ix_ems_events_org_id'), 'ems_events', ['org_id'], unique=False)
    op.create_index(op.f('ix_ems_events_project_id'), 'ems_events', ['project_id'], unique=False)
    op.create_table('ems_validation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('results', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ems_validation_runs_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ems_validation_runs'))
    )
    op.create_index(op.f('ix_ems_validation_runs_project_id'), 'ems_validation_runs', ['project_id'], unique=False)
    op.create_table('ems_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('event_name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=320), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ems_events.id'], name=op.f('fk_ems_alerts_event_id_ems_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_ems_alerts_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ems_alerts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ems_alerts'))
    )
    op.create_index(op.f('ix_ems_alerts_fingerprint'), 'ems_alerts', ['fingerprint'], unique=False)
    op.create_index(op.f('ix_ems_alerts_org_id'), 'ems_alerts', ['org_id'], unique=False)
    op.create_index('ix_ems_alerts_project_status', 'ems_alerts', ['project_id', 'status'], unique=False)
    op.create_table('ems_event_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=320), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ems_events.id'], name=op.f('fk_ems_event_comments_event_id_ems_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ems_event_comments'))
    )
    op.create_index(op.f('ix_ems_event_comments_event_id'), 'ems_event_comments', ['event_id'], unique=False)
    op.create_table('ems_event_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('major', sa.Integer(), nullable=False),
    sa.Column('minor', sa.Integer(), nullable=False),
    sa.Column('patch', sa.Integer(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('author', sa.String(length=320), nullable=False),
    sa.Column('reviewed_by', sa.String(length=320), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['ems_events.id'], name=op.f('fk_ems_event_versions_event_id_ems_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ems_event_versions')),
    sa.UniqueConstraint('event_id', 'version', name=op.f('uq_ems_event_versions_event_id'))
    )
    op.create_index(op.f('ix_ems_event_versions_event_id'), 'ems_event_versions', ['event_id'], unique=False)
    op.create_table('ems_tracking_configs',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('table', sa.String(length=200), nullable=False),
    sa.Column('name_column', sa.String(length=200), nullable=False),
    sa.Column('time_column', sa.String(length=200), nullable=False),
    sa.Column('date_column', sa.String(length=200), nullable=False),
    sa.Column('params_column', sa.String(length=200), nullable=False),
    sa.Column('user_column', sa.String(length=200), nullable=False),
    sa.Column('platform_column', sa.String(length=200), nullable=False),
    sa.Column('version_column', sa.String(length=200), nullable=False),
    sa.Column('drop_threshold', sa.Double(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ems_tracking_configs_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], name=op.f('fk_ems_tracking_configs_source_id_data_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', name=op.f('pk_ems_tracking_configs'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ems_tracking_configs')
    op.drop_index(op.f('ix_ems_event_versions_event_id'), table_name='ems_event_versions')
    op.drop_table('ems_event_versions')
    op.drop_index(op.f('ix_ems_event_comments_event_id'), table_name='ems_event_comments')
    op.drop_table('ems_event_comments')
    op.drop_index('ix_ems_alerts_project_status', table_name='ems_alerts')
    op.drop_index(op.f('ix_ems_alerts_org_id'), table_name='ems_alerts')
    op.drop_index(op.f('ix_ems_alerts_fingerprint'), table_name='ems_alerts')
    op.drop_table('ems_alerts')
    op.drop_index(op.f('ix_ems_validation_runs_project_id'), table_name='ems_validation_runs')
    op.drop_table('ems_validation_runs')
    op.drop_index(op.f('ix_ems_events_project_id'), table_name='ems_events')
    op.drop_index(op.f('ix_ems_events_org_id'), table_name='ems_events')
    op.drop_table('ems_events')
    op.drop_index(op.f('ix_notification_channels_org_id'), table_name='notification_channels')
    op.drop_table('notification_channels')
    op.drop_index(op.f('ix_ems_global_params_org_id'), table_name='ems_global_params')
    op.drop_table('ems_global_params')
    # ### end Alembic commands ###
