"""ems ai drafts

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-05 16:41:39.627268+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0010'
down_revision: str | None = '0009'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ems_tracking_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('app_version', sa.String(length=32), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('truncated', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('created_by', sa.String(length=320), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], name=op.f('fk_ems_tracking_drafts_org_id_organizations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_ems_tracking_drafts_project_id_projects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ems_tracking_drafts'))
    )
    op.create_index(op.f('ix_ems_tracking_drafts_org_id'), 'ems_tracking_drafts', ['org_id'], unique=False)
    op.create_index(op.f('ix_ems_tracking_drafts_project_id'), 'ems_tracking_drafts', ['project_id'], unique=False)
    op.create_table('ems_tracking_draft_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('draft_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('warnings', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reviewed_by', sa.String(length=320), nullable=False),
    sa.Column('result_version', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['ems_tracking_drafts.id'], name=op.f('fk_ems_tracking_draft_items_draft_id_ems_tracking_drafts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['ems_events.id'], name=op.f('fk_ems_tracking_draft_items_event_id_ems_events'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ems_tracking_draft_items'))
    )
    op.create_index(op.f('ix_ems_tracking_draft_items_draft_id'), 'ems_tracking_draft_items', ['draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ems_tracking_draft_items_draft_id'), table_name='ems_tracking_draft_items')
    op.drop_table('ems_tracking_draft_items')
    op.drop_index(op.f('ix_ems_tracking_drafts_project_id'), table_name='ems_tracking_drafts')
    op.drop_index(op.f('ix_ems_tracking_drafts_org_id'), table_name='ems_tracking_drafts')
    op.drop_table('ems_tracking_drafts')
    # ### end Alembic commands ###
