"""Exports of the approved event schemas: JSON Schema and constants/typed helpers for client SDKs."""

from __future__ import annotations

import json
import re
from typing import Any

JSON_TYPES = {
    "string": "string",
    "int": "integer",
    "float": "number",
    "bool": "boolean",
    "enum": "string",
    "timestamp": "string",
    "json": "object",
}


def _pascal(name: str) -> str:
    return "".join(p.capitalize() for p in re.split(r"[_\W]+", name) if p)


def _camel(name: str) -> str:
    p = _pascal(name)
    return p[:1].lower() + p[1:]


def json_schema(
    event: dict[str, Any], params: list[dict[str, Any]], global_params: list[dict[str, Any]]
) -> dict[str, Any]:
    props: dict[str, Any] = {}
    required: list[str] = []
    for p in [*global_params, *params]:
        prop: dict[str, Any] = {"type": JSON_TYPES[p["type"]], "description": p.get("description", "")}
        if p["type"] == "enum":
            prop["enum"] = p.get("enum", [])
        if p["type"] == "timestamp":
            prop["format"] = "date-time"
        props[p["name"]] = prop
        if p.get("required"):
            required.append(p["name"])
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": f"urn:analytics:{event['project']}:{event['name']}:{event['version']}",
        "title": event["name"],
        "description": event.get("description", ""),
        "type": "object",
        "properties": {"event_name": {"const": event["name"]}, **props},
        "required": ["event_name", *required],
        "additionalProperties": False,
    }


TS_T = {
    "string": "string",
    "int": "number",
    "float": "number",
    "bool": "boolean",
    "timestamp": "string",
    "json": "Record<string, unknown>",
}
KT_T = {
    "string": "String",
    "int": "Long",
    "float": "Double",
    "bool": "Boolean",
    "timestamp": "String",
    "json": "Map<String, Any>",
    "enum": "String",
}
SW_T = {
    "string": "String",
    "int": "Int",
    "float": "Double",
    "bool": "Bool",
    "timestamp": "String",
    "json": "[String: Any]",
    "enum": "String",
}
CS_T = {
    "string": "string",
    "int": "long",
    "float": "double",
    "bool": "bool",
    "timestamp": "string",
    "json": "Dictionary<string, object>",
    "enum": "string",
}


def _ts_type(p: dict[str, Any]) -> str:
    if p["type"] == "enum":
        return " | ".join(json.dumps(v) for v in p.get("enum", [])) or "string"
    return TS_T[p["type"]]


def generate(lang: str, events: list[dict[str, Any]], namespace: str = "Analytics") -> str:
    header = "// Generated by the analytics platform event registry. Do not edit by hand.\n"
    if lang == "typescript":
        lines = [header, "export const Events = {"]
        lines += [f"  {_pascal(e['name'])}: {json.dumps(e['name'])}," for e in events]
        lines.append("} as const;\n")
        for e in events:
            lines.append(f"/** {e.get('description', '')} (v{e['version']}) */")
            lines.append(f"export interface {_pascal(e['name'])}Params {{")
            for p in e["params"]:
                lines.append(f"  {p['name']}{'' if p['required'] else '?'}: {_ts_type(p)};")
            lines.append("}\n")
        return "\n".join(lines)
    if lang == "kotlin":
        lines = [header, f"object {namespace}Events {{"]
        lines += [f'    const val {e["name"].upper()} = "{e["name"]}"' for e in events]
        lines.append("}\n")
        for e in events:
            fields = ", ".join(
                f"val {_camel(p['name'])}: {KT_T[p['type']]}{'' if p['required'] else '? = null'}" for p in e["params"]
            )
            body = ", ".join(f'"{p["name"]}" to {_camel(p["name"])}' for p in e["params"])
            lines.append(f"/** {e.get('description', '')} (v{e['version']}) */")
            lines.append(f"data class {_pascal(e['name'])}Event({fields}) {{")
            lines.append(f"    val name: String get() = {namespace}Events.{e['name'].upper()}")
            lines.append(f"    fun params(): Map<String, Any?> = mapOf({body})")
            lines.append("}\n")
        return "\n".join(lines)
    if lang == "swift":
        lines = [header, f"enum {namespace}Event: String {{"]
        lines += [f'    case {_camel(e["name"])} = "{e["name"]}"' for e in events]
        lines.append("}\n")
        for e in events:
            lines.append(f"/// {e.get('description', '')} (v{e['version']})")
            lines.append(f"struct {_pascal(e['name'])}Params {{")
            for p in e["params"]:
                lines.append(f"    let {_camel(p['name'])}: {SW_T[p['type']]}{'' if p['required'] else '?'}")
            lines.append("    var dictionary: [String: Any] {")
            lines.append("        var d: [String: Any] = [:]")
            for p in e["params"]:
                v = _camel(p["name"])
                lines.append(
                    f'        d["{p["name"]}"] = {v}'
                    if p["required"]
                    else f'        if let v = {v} {{ d["{p["name"]}"] = v }}'
                )
            lines.append("        return d")
            lines.append("    }")
            lines.append("}\n")
        return "\n".join(lines)
    if lang == "csharp":
        lines = [
            header,
            "using System.Collections.Generic;\n",
            f"namespace {namespace}",
            "{",
            "    public static class Events",
            "    {",
        ]
        lines += [f'        public const string {_pascal(e["name"])} = "{e["name"]}";' for e in events]
        lines.append("    }\n")
        for e in events:
            lines.append(f"    /// <summary>{e.get('description', '')} (v{e['version']})</summary>")
            lines.append(f"    public sealed class {_pascal(e['name'])}Params")
            lines.append("    {")
            for p in e["params"]:
                t = CS_T[p["type"]]
                nullable = "" if p["required"] or t.startswith(("string", "Dictionary")) else "?"
                lines.append(f"        public {t}{nullable} {_pascal(p['name'])};")
            lines.append("        public Dictionary<string, object> ToDictionary()")
            lines.append("        {")
            lines.append("            var d = new Dictionary<string, object>();")
            for p in e["params"]:
                lines.append(f'            if ({_pascal(p["name"])} != null) d["{p["name"]}"] = {_pascal(p["name"])};')
            lines.append("            return d;")
            lines.append("        }")
            lines.append("    }\n")
        lines.append("}")
        return "\n".join(lines)
    raise ValueError(lang)
